### ISSUE TITLE
AntiDump always true

### ISSUE THREAD

**Issue by TheMercen133** [aimardcr/AndroidNativeGuard#3]
Antidump always returns true, even I don't do anything like dumping the memory

Results :
AntiDump::execute len: 16
AntiDump::execute event->mask: 32

Tested on:
- Android 13 arm64 (device)
- Android 13 x86_64 (emulator)
- Android 9 x86_64/x86 (emulator)

**Comment by aimardcr** [comment]
Opening or reading /proc/self/maps will trigger the module, can you show me the screenshot of the app? or maybe steps that you did?

**Comment by TheMercen133** [comment]
> Opening or reading /proc/self/maps will trigger the module, can you show me the screenshot of the app? or maybe steps that you did?

oh yeah I see, I have a method that checks the processing memory xD
