### ISSUE TITLE
Crash when start

### ISSUE THREAD

**Issue by datfooldive** [aimardcr/AndroidNativeGuard#5]
![Screenshot_20230816-104511_LogFox.png](https://github.com/aimardcr/AndroidNativeGuard/assets/110718021/3768b0a5-e7a5-43f9-89e3-c354ec571838)

![Screenshot_20230816-104522_AndroidIDE.png](https://github.com/aimardcr/AndroidNativeGuard/assets/110718021/99dcde0f-b5d8-4cc8-9edd-5db8b7f7be3c)

try build and run it but got this issue

**Comment by aimardcr** [comment]
This project is meant to be used in Android Studio.
