### ISSUE TITLE
Infinity checking

### ISSUE THREAD

**Issue by abdulazizumarovich** [aimardcr/AndroidNativeGuard#9]
Does it even stop checking?
All services are writing huge number of logs without result. Is it normal?
![image](https://github.com/aimardcr/AndroidNativeGuard/assets/34490647/c09c296b-c81b-4f1d-9a48-17c82fba6122)

**Comment by aimardcr** [comment]
Well, logs are opsional and for debugging purpose only. You can empty the function definition to prevent loggings.

**Comment by abdulazizumarovich** [comment]
But, how much time it needs to complete checks? It took ~20minutes without stop

**Comment by aimardcr** [comment]
Some modules are running routinely, and some just run once.

**Comment by abdulazizumarovich** [comment]
Thank you!
